In [8]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Input words
x = np.array([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])

# POS tags
y = np.array([
    [1, 2, 1],
    [2, 1, 2],
    [1, 1, 2]
])

# Create LSTM model
model = Sequential()

model.add(Embedding(input_dim=10, output_dim=8, input_length=3))
model.add(LSTM(16, return_sequences=True))
model.add(Dense(3, activation="softmax"))

# Compile model
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

# Train model
model.fit(x, y, epochs=10)

# Predict
result = model.predict(x)

print("Prediction:")
print(result)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.4444 - loss: 1.0996
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.4444 - loss: 1.0977
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.4444 - loss: 1.0957
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4444 - loss: 1.0938
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4444 - loss: 1.0919
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.4444 - loss: 1.0900
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.4444 - loss: 1.0880
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.4444 - loss: 1.0861
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4444 - loss: 1.0841
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4444 - loss: 1.0822
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
Prediction:
[[[0.32464993 0.33666635 0.33868372]
  [0.3204072  0.33723107 0.3423617 ]
  [0.3178522  0.33731896 0.34482884]]

 [[0.32

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 1.1010
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.0000e+00 - loss: 1.1004
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0000e+00 - loss: 1.0999
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.0000e+00 - loss: 1.0994
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0000e+00 - loss: 1.0989
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.0000e+00 - loss: 1.0984
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.3333 - loss: 1.0979
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3333 - loss: 1.0974
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3333 - loss: 1.0970
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3333 - loss: 1.0965
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step
Predicted Tags:
[[1 2 2]]
